### ISSUE TITLE
md-tabs problem

### ISSUE THREAD

**Issue by mist3r3** [chymz/ng2-ckeditor#124]
Bug, feature request, or proposal:
Bug

What is the expected behavior?
When adding ckeditor from ng2-ckeditor it should work

What is the current behavior?
I cannot render the ckeditor properly. If you put the ckeditor in the first tab it works until you change tab (and then even if you come back to the first tab the ckeditor won't work)

What are the steps to reproduce?
http://plnkr.co/edit/f6YoVj2cpVXTl2sAFvQy?p=preview

What is the use-case or motivation for changing an existing behavior?
Ie believe there is something blocking the initialization process or something like that.

Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 4, material 2 beta 5

I post it here also because I don't know if the problem comes from md-tabs or from the widget itself.

**Comment by loganfarr** [comment]
I have a similar problem. When the component is first loaded, even if you are not on the CKEditor tab, I get the following error:
ERROR TypeError: Cannot read property 'unselectable' of null

I thought it was related to #44 but turns out it is related to md-tabs.

**Comment by steve-todorov** [comment]
We've discussed this in [material2#4734](https://github.com/angular/material2/issues/4734) but one of the collaborators closed the issue saying it was not a material bug. I hope @chymz  has an idea what might be causing this.

**Comment by chymz** [comment]
Someone can make a sample repo ?
thanks !

**Comment by steve-todorov** [comment]
@chymz you can check out my comment at the material2 repo which has a plunker as well - https://github.com/angular/material2/issues/4734#issuecomment-303898724 

Below I've copy/pasted the comment for archive purpose:

---

I'm experiencing the same issue as well and I'm not sure if this is a `material2`, `ckeditor` or `ng2-ckeditor` issue. 

If you have one instance of `ckeditor` and you have it in the first tab - it will work. However, if you navigate away to another tab and go back to the first one - you will not be able to click anything nor edit. Here is a [plunker](http://plnkr.co/edit/aCYY4SFCtXreiB4azR77?p=preview) example which reproduces the issue.

Example 1:
![image](https://cloud.githubusercontent.com/assets/2303663/26432301/754b3ae6-4103-11e7-879f-48b329624b44.png)

Example 2 (after clicking "test 2" tab and going back to "test 1"):
![image](https://cloud.githubusercontent.com/assets/2303663/26432316/9366441c-4103-11e7-85d2-e32e0ed7d2a3.png)

Sometimes the ckeditor isn't even rendered at all after tab change.

In the console you could see (from time to time) the following exception:
> ERROR TypeError: Cannot read property 'unselectable' of null
    at b (https://cdn.ckeditor.com/4.5.11/full-all/ckeditor.js:309:119)
    at a.<anonymous> (https://cdn.ckeditor.com/4.5.11/full-all/ckeditor.js:305:337)
    at a.h (https://cdn.ckeditor.com/4.5.11/full-all/ckeditor.js:10:70)
    at a.window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.event.CKEDITOR.event.fire (https://cdn.ckeditor.com/4.5.11/full-all/ckeditor.js:11:433)
    at a.window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.editor.CKEDITOR.editor.fire (https://cdn.ckeditor.com/4.5.11/full-all/ckeditor.js:13:97)
    at a.fireOnce (https://cdn.ckeditor.com/4.5.11/full-all/ckeditor.js:12:86)
    at a.window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.editor.CKEDITOR.editor.fireOnce (https://cdn.ckeditor.com/4.5.11/full-all/ckeditor.js:13:253)
    at Object.<anonymous> (https://cdn.ckeditor.com/4.5.11/full-all/ckeditor.js:237:23)

 What could be causing this? Is there anything going on behind the scenes when you click a tab (i.e. something like `ngOnDestroy`, perhaps) that needs to be implemented in `ng2-ckeditor`?

**Comment by chymz** [comment]
Well i've a dirty fix for this : https://github.com/chymz/ng2-ckeditor/commit/7564f2b06fe955ed9692071ed22055e4181a026f

If someone have a better solution, i'll take it !

**Comment by steve-todorov** [comment]
This fix seems to be solving the problem for me! :)

**Comment by hellosandeep** [comment]
hi steve-todorov,
i had go through your plunker link unable to see example. can you share me what changes required will be appreciated.

**Comment by steve-todorov** [comment]
@hellosandeep it seems that the plunker example is no longer working but I don't have time to deal with that right now. It was an example which reproduces the issue I had when using multiple ckeditors inside `md-tab`. If you want to see the fix - check @chymz's comment. It works fine for me.

**Comment by NeonSilk1** [comment]
@chymz @steve-todorov I've had the same issue, I managed to get it solved without modifying ng2-ckeditor. I put an *ngIf condition in a surrounding div to check if the tab is active before showing the ckeditor. CK does not instantiate until it is showing from the ngIf

**Comment by steve-todorov** [comment]
@NeonSilk1 I have been testing this for about a week now and it seems to be working better. On our back-end we have a page with few instances of ckeditor and that was hurting the pageload as well as lagging when interacting. If you use `*ngIf` though, it works a lot smoother and faster. I am using the new `md-expansion-panel` now but I'm sure this solution will work in `md-tabs` as well! :)

**Comment by chymz** [comment]
Fixed in 1.1.12

**Comment by nikosgpet** [comment]
I am using version 1.2.0 and the bug still exists. The moment I change tab, the ckeditor in the previous tab stops working

**Comment by kzimny** [comment]
The best solution is to work with `*ngIf`. If you change the tab set the visibility of editors in hidden tabs to false. Look at similar [question ](https://github.com/chymz/ng2-ckeditor/issues/133#issuecomment-352416227) asked a few weeks ago.
